name: 10-Channel Super-Fast Auto-Uploader

on:
  schedule:
    # यह मशीन भारतीय समयानुसार हर 6 घंटे में दिन में 4 बार चलेगी
    - cron: '0 1,7,13,19 * * *'
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick ffmpeg fonts-deva
          sudo rm -f /etc/ImageMagick-6/policy.xml

      - name: Install Python Libraries
        run: |
          pip install requests edge-tts moviepy==1.0.3 pillow google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Run 10-Channel Master Machine
        run: |
          python main.py
